// CONFIGURACIONES DE CONEXION A ESSALUD
export const USUARIO = '47813783';
export const CONTRASEÑA = 'Khronos92';
export const CENTRO_ASISTENCIAL = 822;
export const NOMBRE_IPRESS = 'IPRESS SAN CARLOS';

// CONFIGURACIONES DE DASHBOARD GENERAL
export const DIAS_GRAFICO_CITAS = 15;
export const FECHAACTUAL = new Date(Date.now() - (86400000 * 0));
